---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-task-deployment
  labels:
    app: debug-task-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-task-app
  template:
    metadata:
      labels:
        app: debug-task-app
    spec:
      containers:
        
        - name: nginx
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: debug-task
              mountPath: /uploads # the path of the files in the app is in /uploads/ instead of /app/uploads/
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
        
        - name: app
          image: alpacked/test-task # Better to use the versioning system instaed of 'latest' tag.
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-storage
              mountPath: /app/data
            - name: debug-task
              mountPath: /uploads

      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: debug-task
          persistentVolumeClaim:
            claimName: debug-task-pvc
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-storage-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: debug-task-app
data:
  default.conf: |
    server {
        listen 8081;

        # It is beeter to implemet /health as a separate endpoint
        location /health {
            access_log off;   # turn off logs to avoid spam
            
            proxy_pass http://127.0.0.1:8080/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /uploads {
            return 200;
            root /uploads;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: debug-task-service
spec:
  selector:
    app: debug-task-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debug-task-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Add PVC for app-storage data in /app/data/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi